#version: '3'

services:
  frontend:
    restart: always
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules # Prevents overwriting node_modules
      - ./frontend:/app   # Mounts the frontend directory for live updates
    environment:
      - CHOKIDAR_USEPOLLING=true # Improves live reload in Docker
  api:
    restart: always
    build: ./api
    ports:
      - "5050:5050"
    volumes:
      - ./api:/app
