#version: '3'

services:
  frontend:
    restart: always
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules # Prevents overwriting node_modules
      - ./frontend:/app   # Mounts the frontend directory for live updates
    environment:
      - CHOKIDAR_USEPOLLING=true # Improves live reload in Docker
  api:
    restart: always
    build: ./api
    ports:
      - "5050:5050"
    volumes:
      - ./api:/app
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    # volume from mongo virtual machine mapped to container folder
    volumes:
      - mongodb_data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo

# volume inside docker virtual machine
volumes:
    mongodb_data:
